/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#93000d",
        "secondary": "#5f5e5e",
        "on-secondary-fixed-variant": "#474746",
        "on-error-container": "#93000a",
        "surface-container": "#eeeeee",
        "inverse-primary": "#ffb4ac",
        "on-tertiary-fixed": "#001f27",
        "inverse-on-surface": "#f1f1f1",
        "inverse-surface": "#2f3131",
        "on-primary-container": "#fffbff",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#72d4ef",
        "on-surface": "#1a1c1c",
        "primary": "#F03030",
        "on-background": "#1a1c1c",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "surface-bright": "#f9f9f9",
        "primary-container": "#db322f",
        "surface-tint": "#F03030",
        "on-secondary-fixed": "#1c1b1b",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#c8c6c5",
        "surface-container-highest": "#e2e2e2",
        "primary-fixed-dim": "#ffb4ac",
        "on-primary-fixed": "#410002",
        "on-surface-variant": "#5b403d",
        "background": "#F5F5F5",
        "surface-variant": "#e2e2e2",
        "secondary-container": "#e2dfde",
        "surface-container-high": "#e8e8e8",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#004e5d",
        "surface-container-low": "#f3f3f3",
        "surface": "#F5F5F5",
        "on-tertiary-container": "#f9fdff",
        "tertiary-fixed": "#afecff",
        "tertiary": "#006578",
        "on-secondary": "#ffffff",
        "primary-fixed": "#ffdad6",
        "secondary-fixed": "#e5e2e1",
        "on-secondary-container": "#636262",
        "outline": "#906f6c",
        "surface-dim": "#dadada",
        "outline-variant": "#e4beb9",
        "tertiary-container": "#008097",
        "on-error": "#ffffff",
        // Keep old ones so other pages don't break
        'primary-dark': '#C0392B',
        'primary-light': '#ffdad6',
        dark: '#1A1A1A',
        'brand-bg': '#F5F5F5',
      },
      fontFamily: {
        headline: ["Cairo", "sans-serif"],
        body: ["Cairo", "sans-serif"],
        label: ["Cairo", "sans-serif"],
        sans: ['Cairo', 'Inter', 'sans-serif'],
        cairo: ['Cairo', 'sans-serif'],
        tajawal: ['Tajawal', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        'card': '12px',
        'btn': '8px',
        'pill': '24px',
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      keyframes: {
        pulse_red: {
          '0%, 100%': { boxShadow: '0 0 0 0 rgba(240, 48, 48, 0.4)' },
          '50%': { boxShadow: '0 0 0 10px rgba(240, 48, 48, 0)' },
        },
        countup: {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        pulse_red: 'pulse_red 2s ease-in-out infinite',
        countup: 'countup 0.5s ease-out forwards',
      },
    },
  },
  plugins: [],
}
